// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datahubio_countrycodes.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DataHubIo_CountryCodes module
	public static void aCT_CountryCodes_Update(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "DataHubIo_CountryCodes.ACT_CountryCodes_Update", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static datahubio_countrycodes.proxies.CountryFlag countryFlag_Ensure_CWF(IContext context, datahubio_countrycodes.proxies.CountryCode _countryCode)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CountryCode", _countryCode == null ? null : _countryCode.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "DataHubIo_CountryCodes.CountryFlag_Ensure_CWF", params);
			return result == null ? null : datahubio_countrycodes.proxies.CountryFlag.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static datahubio_countrycodes.proxies.CountryFlag countryFlag_Ensure_Flagpedia(IContext context, datahubio_countrycodes.proxies.CountryCode _countryCode)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CountryCode", _countryCode == null ? null : _countryCode.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "DataHubIo_CountryCodes.CountryFlag_Ensure_Flagpedia", params);
			return result == null ? null : datahubio_countrycodes.proxies.CountryFlag.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static datahubio_countrycodes.proxies.CountryFlag countryFlag_Ensure_FoTW(IContext context, datahubio_countrycodes.proxies.CountryCode _countryCode)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CountryCode", _countryCode == null ? null : _countryCode.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "DataHubIo_CountryCodes.CountryFlag_Ensure_FoTW", params);
			return result == null ? null : datahubio_countrycodes.proxies.CountryFlag.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static datahubio_countrycodes.proxies.CountryFlag countryFlag_Ensure_FoTW_2(IContext context, datahubio_countrycodes.proxies.CountryCode _countryCode)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CountryCode", _countryCode == null ? null : _countryCode.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "DataHubIo_CountryCodes.CountryFlag_Ensure_FoTW_2", params);
			return result == null ? null : datahubio_countrycodes.proxies.CountryFlag.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static datahubio_countrycodes.proxies.CountryCode getCountryCode(IContext context, java.lang.String _iSO3166_1_Alpha_2, java.lang.String _iSO3166_1_Alpha_3)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ISO3166_1_Alpha_2", _iSO3166_1_Alpha_2);
			params.put("ISO3166_1_Alpha_3", _iSO3166_1_Alpha_3);
			IMendixObject result = (IMendixObject)Core.execute(context, "DataHubIo_CountryCodes.GetCountryCode", params);
			return result == null ? null : datahubio_countrycodes.proxies.CountryCode.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean string2Boolean(IContext context, java.lang.String _string)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("String", _string);
			return (java.lang.Boolean)Core.execute(context, "DataHubIo_CountryCodes.String2Boolean", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}